---
    - name: restart apache
      service:
        name: apache2
        state: restarted
      become: yes
    - name: restart zabbix-server
      service:
        name: zabbix-server
        state: restarted
      become: yes
    - name: restart zabbix-agent
      service:
        name: zabbix-agent
        state: restarted
      become: yes
