---
  - name: Instalando o pacote deb do zabbix pela internet
    ansible.builtin.apt:
      deb: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-1+ubuntu22.04_all.deb
    become: yes
  - name: Atualizando Repositorio
    ansible.builtin.apt:
      update_cache: yes
    become: yes
  - name: Instalando a lista de Zabbix-serve Zabbix Frontend e Mysql
    ansible.builtin.apt:
      pkg:
      - zabbix-server-mysql
      - zabbix-frontend-php
      - zabbix-apache-conf
      - zabbix-sql-scripts
      - zabbix-agent
    become: yes
  - name: Instalando depedencias em mysql
    ansible.builtin.apt:
      pkg:
      - mysql-server
      - python3-pymysql
    become: yes
  - name: Criando a base de dados chamado zabbix
    community.mysql.mysql_db:
      name: zabbix
      state: present
      encoding: utf8mb4
      collation: utf8mb4_bin
      login_unix_socket: /run/mysqld/mysqld.sock
    become: yes
  - name: Criando o usuario zabbix do banco de dados
    community.mysql.mysql_user:
      name: zabbix
      password: '@dminzabbix'
      priv: 'zabbix.*:ALL'
      state: present
      login_unix_socket: /run/mysqld/mysqld.sock
      host: 'localhost'
    become: yes
  - name: setando um teste
    community.mysql.mysql_query:
      login_db: zabbix
      query: 'SET GLOBAL log_bin_trust_function_creators = 1;'
      login_unix_socket: /run/mysqld/mysqld.sock
    become: yes
  - name: Descompactar e importar o arquivo SQL para o MySQL
    shell: zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -uzabbix -p'@dminzabbix' zabbix
    args:
      executable: /bin/bash
    become: yes
  - name: setando um teste para default
    community.mysql.mysql_query:
      login_db: zabbix
      query: 'SET GLOBAL log_bin_trust_function_creators = 0;'
      login_unix_socket: /run/mysqld/mysqld.sock
    become: yes
  - name: Ensure SELinux is set to enforcing mode
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_server.conf
      regexp: 'DBPassword=password'
      line: DBPassword=@dminzabbix
    become: yes
